#!/usr/bin/python3

from enum import Enum
from itertools import product
import fileinput
import random
import sys

DEBUG=False

# using a constant seed for deterministic shuffling
rand=random.Random(0)

class State(Enum):
    START = 1
    STRING = 2
    OTHER = 3
    NUMERIC = 4
    WORD = 5
    COMMENT = 6
    SPACE = 7
    PSQLCMD = 8
    PSQLVAR = 9

def tokenize(input):
    """Turn the input string into a list of strings based on simple
    tokenization rules (basically quoted strings are a single
    token). there is implicit whitespace between all tokens.
"""
    state = State.START
    ret = ''
    qc = ''

    i = -1

    while i < len(input) - 1:
        i = i + 1
        c = input[i]
        nextc = input[i+1] if i < len(input) - 1 else None

        if state == State.STRING:
            ret = ret + c
            if c == qc:
                if nextc == qc:
                    # SQL-style double-quoted strings, like yuck, srsly?!
                    # just append another one and skip the next char, leaving in string mode
                    ret = ret + c
                    i = i + 1
                else:
                    if len(ret) > 0:
                        yield (ret,state)
                        ret = ''
                    state = State.START
        elif state == State.COMMENT:
            # we are discarding comments, so just ignore anything that isn't our closing sequence
            if qc == "\n" and c == "\n":
                state = State.START
            elif c == "*" and nextc == '/':
                state = State.START
                i = i + 1
        elif state == State.PSQLCMD:
            if DEBUG: print(f'got pt PSQLCMD')
            # continue parsing the psql command until we hit a newline or
            # another psql command. TODO: be careful about strings quoting in
            # this routine; probably need to at least single/double quoting.
            # For now just skip caring about quoting: what are you going to do,
            # fix it and submit a PR?

            if c == "\n" or c == '\\':
                # explicitly *not* including the trailing newline in our token;
                # spacing rules will figure it out contextually right after I
                # write the logic
                yield (ret.strip(),state)
                state = State.START
                ret = ''
                if c == '\\':
                    # back up so we can start our processing at the slash next
                    # time around
                    i = i - 1
            else:
                ret = ret + c
        elif state == State.PSQLVAR:
            if DEBUG: print(f'got PSQLVAR')
                # PSQLVAR is just :\w+ for now, TODO: add '' and ""-quoted vars
            if c.isalnum():
                # explicitly *not* including the trailing newline in our token;
                # spacing rules will figure it out contextually right after I
                # write the logic
                ret = ret + c
            else:
                yield (ret.strip(),state)
                state = State.START
                ret = ''
                i = i - 1
        else:
            if c in "\"'":
                ctype = State.STRING
                qc = c
            elif c == '-' and nextc == '-':
                ctype = State.COMMENT
                qc = '\n'
            elif c == '/' and nextc == '*':
                ctype = State.COMMENT
                qc = '/'
            elif c.isspace():
                ctype = State.SPACE
            elif (c.isdigit() and state != State.WORD) or (c == '.' and state == State.NUMERIC):
                ctype = State.NUMERIC
            elif c.isalnum() or c == '_':
                ctype = State.WORD
            elif c == ':':
                if nextc == ':':
                    ctype = State.OTHER
                    # required hack to skip past the double-::
                    c = "::"
                    i = i + 1
                else:
                    # looks like this is a psql variable
                    ctype = State.PSQLVAR
            elif c == '\\':
                if nextc == '\\':
                    ctype = State.OTHER
                    # required hack to skip past the double-slash
                    c = "\\\\"
                    i = i + 1
                else:
                    # looks like this is a psql command; terminated by another psql cmd or a newline
                    ctype = State.PSQLCMD
                    if DEBUG: print(f'state:{state},ret:{ret},c:{c},nextc:{nextc}')
            else:
                ctype = State.OTHER

            if DEBUG and ctype == State.START: sys.stderr.write(f"XXXX somehow got a Start token; this shouldn't happen: {c,i}\n")

            if len(ret) > 0 and state != ctype:
                yield (ret,state)
                ret = ''
            if ctype != State.COMMENT:
                ret = ret + c
            state = ctype
    if len(ret) > 0: yield (ret,state)

def idents():
    lists = []
    while True:
        chars = [chr(n) for n in range(ord('a'), ord('z') + 1)] + [chr(n) for n in range(ord('A'), ord('Z') + 1)]
        rand.shuffle(chars)
        lists.append(chars)
        for c in product(*lists):
            yield ':' + (''.join(c))

ident = iter(idents())
xform = dict()

out = []
last_st = None
for line in fileinput.input():
    for t,st in tokenize(line):
        if DEBUG: sys.stderr.write(f"{(t,st)}\n")
        if st not in [State.COMMENT, State.SPACE]:
            if DEBUG: sys.stderr.write(f"---> CHECKING FOR SPACING: this token: {st}; last token: {last_st} <---\n")
            if last_st == State.PSQLCMD and st != State.PSQLCMD:
                out.append("\n")
            elif State.OTHER not in [last_st, st]:
                if DEBUG: sys.stderr.write("---> FORCING SPACING <---\n")
                if last_st: out.append(' ')
            last_st = st
            if st == State.WORD and len(t) > 2:
                # we are a transformable token
                key = xform.setdefault(t.lower(), next(ident))
                if DEBUG: sys.stderr.write(f"---> CHOOSING REPLACEMENT KEY {key} FOR TOKEN: {t} <---\n")
                out.append(key)
            else:
                out.append(t)
for k,v in sorted(xform.items()):
    print(f'\set {v.removeprefix(":")} {k}',end=' ')
print()
#for o in out:
print(''.join(out))
